name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose

    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        
    - name: Set env
      run:  echo ::set-env name=MYTEST::$(date "+%Y.%m.%d")
      
    - name: Define Env Vars
      run: |
          echo MYTEST=${MYTEST}
          
    - name: Install Dependencies
      run: |
        sudo apt-get install libgtk-3-dev
          
    - name: Build | Compile
      run: cargo check
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}.${{ MYTEST }}
        release_name: Release ${{ github.ref }}.${{ MYTEST }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
